name: themovie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  freezed_annotation: ^2.1.0
  cached_network_image: ^3.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  injectable_generator: ^1.5.4
  build_runner: ^2.2.1
  freezed: ^2.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
flutter_native_splash:
  image: assets/images/logo.png
  color: "#0d253f"